### PR TITLE
Adding support for check-contents

### PR DESCRIPTION
**Pull request by renatoagds**
This PR transform the `flow` path into a option and create a new option called `path`.

With this new format, we can allow flow-vim-quickfix to use [`flow check-contents`](https://flowtype.org/docs/cli.html#_) that is a option to flow a unique file instead of whole project, this is very useful and reduce the flow log noisy.

The new way to use `flow-vim-quickfix` is:

`flow-vim-quickfix --flow=path_to_flow --path=path_to_file`

The new config to use `check-contents` would be: 

```
function! FlowArgs()
  let g:file_path = expand('#:p')
  return ['-c', g:flow_path.' check-contents < '.g:file_path.' --json | flow-vim-quickfix --path='.g:file_path]
endfunction

let g:flow_maker = {
\ 'exe': 'sh',
\ 'args': function('FlowArgs'),
\ 'errorformat': '%E%f:%l:%c\,%n: %m',
\ 'cwd': '%:p:h'
\ }
```

Is necessary to receive/pass path, because the flow json output do not contain the path if you're using check-contents.

### CODE REVIEW

**Comment by ryyppy** [comment]
So this will enable us to run the flow_maker on the current file I am editing and not on the project-level? :-)

**Comment by ryyppy** [comment]
We will need tests and README docs as well, if this is the case!
Also I am not sure why you need the `--strip-root` argument in your flow_maker config?

**Comment by renatoagds** [comment]
@ryyppy yes, this will enable to run flow in the current file. I update the way to write flow_maker config since it wasn't updating the current file.

I will add tests and update README asap 👍

**Comment by ryyppy** [comment]
Maybe add multiple README sections for those who want to use `check-contents` or a project-wide `flow_maker`, if possible :-) ... cool stuff!

**Comment by renatoagds** [comment]
@ryyppy closing this one since I started to look deep into `flow` and changed the way to flow just one file and in the new way is not necessary to update nothing here in `flow-vim-quickfix`, but I'll open a new PR adding the way to flow just one file in `README`.

**Pull request closed without merging**
